{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}  
ARG BASE=docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE AS base

ARG docker_container_name
ARG image_version

{% if docker_dummy_http_debs.strip() -%}
{{ copy_files("debs/", docker_dummy_http_debs.split(' '), "/debs/") }}
{{ install_debian_packages(docker_dummy_http_debs.split(' ')) }}
{%- endif %}

COPY ["docker_init.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["dummy_http.conf", "/etc/supervisor/conf.d/"]


RUN chmod +x /usr/bin/docker_init.sh

# Expose HTTP port
EXPOSE 8080

# Pass the image_version to container
ENV IMAGE_VERSION=$image_version

ENV DEBIAN_FRONTEND=noninteractive
ENTRYPOINT ["/usr/bin/docker_init.sh"]