DOCKER_DUMMY_HTTP_STEM = docker-dummy-http
DOCKER_DUMMY_HTTP = $(DOCKER_DUMMY_HTTP_STEM).gz

$(DOCKER_DUMMY_HTTP)_PATH = $(DOCKERS_PATH)/$(DOCKER_DUMMY_HTTP_STEM)
$(DOCKER_DUMMY_HTTP)_VERSION = 1.0.0
$(DOCKER_DUMMY_HTTP)_PACKAGE_NAME = dummy-http
$(DOCKER_DUMMY_HTTP)_CONTAINER_NAME = dummy-http

# Make the dummy container depend on your deb
$(DOCKER_DUMMY_HTTP)_DEPENDS = $(DUMMY_HTTP_PKG)

# Ensure docker-config-engine-bookworm is built before this
$(DOCKER_DUMMY_HTTP)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

# Inherit debug dependencies from config-engine-bookworm
$(DOCKER_DUMMY_HTTP)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_DUMMY_HTTP)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_DUMMY_HTTP)_RUN_OPT += -t
$(DOCKER_DUMMY_HTTP)_RUN_OPT += -p 8080:8080/tcp

SONIC_DOCKER_IMAGES += $(DOCKER_DUMMY_HTTP)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_DUMMY_HTTP)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_DUMMY_HTTP)
