DOCKER_DUMMY_HTTP_STEM = docker-dummy-http
DOCKER_DUMMY_HTTP = $(DOCKER_DUMMY_HTTP_STEM).gz

$(DOCKER_DUMMY_HTTP)_PATH = $(DOCKERS_PATH)/$(DOCKER_DUMMY_HTTP_STEM)

# Make the dummy container depend on your deb
$(DOCKER_DUMMY_HTTP)_DEPENDS = $(DUMMY_HTTP_PKG)

# Inherit debug dependencies from config-engine-bookworm
$(DOCKER_DUMMY_HTTP)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_DUMMY_HTTP)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

# Ensure docker-config-engine-bookworm is built before this
$(DOCKER_DUMMY_HTTP)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

SONIC_DOCKER_IMAGES += $(DOCKER_DUMMY_HTTP)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_DUMMY_HTTP)
